export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
    USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',

    USER_LOAD_REQUEST: 'USER_LOAD_REQUEST',
    USER_LOAD_FAILURE: 'USER_LOAD_FAILURE',
    USER_LOAD_SUCCESS: 'USER_LOAD_SUCCESS',

    USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
    USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}

export const userConstants = {

    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_RESET: 'UPDATE_PROFILE_RESET',

    UPDATE_PASSWORD_REQUEST: 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_FAILURE: 'UPDATE_PASSWORD_FAILURE',
    UPDATE_PASSWORD_SUCCESS: 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_RESET: 'UPDATE_PASSWORD_RESET',

    FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
    FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',

    NEW_PASSWORD_REQUEST: 'NEW_PASSWORD_REQUEST',
    NEW_PASSWORD_FAILURE: 'NEW_PASSWORD_FAILURE',
    NEW_PASSWORD_SUCCESS: 'NEW_PASSWORD_SUCCESS',

    ALL_USERS_REQUEST: 'ALL_USERS_REQUEST',
    ALL_USERS_FAILURE: 'ALL_USERS_FAILURE',
    ALL_USERS_SUCCESS: 'ALL_USERS_SUCCESS',

    CLEAR_ERRORS: 'CLEAR_ERRORS',
}